AWS_ACCESS_KEY_ID = 'XXXXXXXXXXXXXXXXXXXXX' # Place Your Keys Here
AWS_SECRET_ACCESS_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' # Place Your Keys Here
youtube_dev_keys = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' # Place Your Keys Here